config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to=>"dashboards#welcome"

  resources :dashboards
  get "welcome", to: "dashboards#welcome"
  get "base", to: 'dashboards#index'

  resources :attendances, only: [:index, :create, :update] do
    get :payments, on: :collection
    get :payment_done, on: :collection
    post :delete_record, on: :collection
  end
  
  resources :billings, only: [:new, :create, :edit, :show, :update, :index, :destroy] do 
    put :update_status, on: :member
    get :cancel, on: :member
    post :delevery_done, on: :member
    put :delevery, on: :member
    get :get_bill_no, on: :collection
    patch :update_final_billing, on: :member
  	resources :carts, only: [:create, :new, :destroy]

  end 
  resources :customers, only: [:index, :show, :new, :create, :destroy] do 
    post :send_reminder_sms, on: :member
    get :reminder_sms, on: :member
    post :send_bulk_sms, on: :collection
    get :download, on: :collection
  end

  resources :employees, only: [:index, :create, :update, :destroy]

  resources :accounts, only: [:index, :create, :update] do
    post :delete_record, on: :collection
  end
  resources :vendor_billings do 
    get :get_monthaly_record, on: :collection
    get :payment_done, on: :collection
    get :change_amount, on: :member
    post :update_amount, on: :member
    post :delete_record, on: :collection
  end
  resources :extra, only: [:index] do
    post :create_item, on: :collection
    post :create_service, on: :collection
    get :billing, on: :collection
  end

  resources :csvs, only: [:index] do 
    get :get_monthly_record, on: :collection
    get "/download/:year/:month",  to: "csvs#download", on: :collection
    get "/destroy/:year/:month",  to: "csvs#destroy", on: :collection
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :billings
  has_many :balances
  validates :phone, uniqueness: true, allow_nil: true
  #scope
  scope :uniq_phone, -> {where("phone IS NOT ?", nil).pluck(:phone)}
  default_scope {order('id DESC')}

  def self.with_organization organization_id
  	Customer.joins(:billings).where('billings.organization_id = ?',organization_id.to_i)
  end

  def send_sms message
  	Sms.send_sms(message, phone)
  end

  def balance_amount
    if self.balances.present?
      self.balances.last.status == "pending" ? self.balances.last : nil
    end 
  end

  def self.to_csv(options = {})
    # attributes = %w{id name}
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |customer|
        csv << customer.attributes.values
      end
    end
  end

  def customer_balance_amount 
    if self.balances.present?
      advance_amount = self.balances.pending.sum(:advance_amount)
      due_amount = self.balances.pending.sum(:due_amount)
      [advance_amount, due_amount]
    else
      [0,0]
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # before_action :check_admin_user
  skip_before_action :verify_authenticity_token, only: [:download]
  before_action :get_organizations, only: [:index]
  before_action :find_customer, only: [:reminder_sms, :send_reminder_sms, :show, :destroy]

  def index
    @q = Customer.ransack(params[:q])
    @customers = @q.result.order('id DESC').paginate(:page => params[:page], :per_page => 30)
    respond_to do |format|
      format.html
      format.csv {send_data @customers.to_csv, disposition: :inline}
    end
  end

  def show
    @balances = @customer.balances.paginate(:page => params[:page], :per_page => 10)
  end

  def reminder_sms
  end

  def send_reminder_sms
    res = @customer.send_sms(params[:message])
    if res["status"] == "success"
      flash[:success] = "Message sent successfully"
    else
      flash[:danger] = res["message"]
    end
    redirect_to billings_path(page: params[:page])
  end

  def send_bulk_sms
    params[:customer_numbers].each do |number|
      Sms.send_sms(params[:sms], number)
    end
    flash[:success] = "Message sent successfully"
    redirect_to customers_path
  end

  def download
    # binding.pry
    @customers = Customer.all#.where(id: params[:ids])
      respond_to do |format|
        format.csv {send_data @customers.to_csv, filename: "#{Date.today}.csv", disposition: :attachment}
      end
  end

  def destroy
    @balance = @customer.balances.find_by(id: params[:balance_id])
    @balance.delete
    redirect_to customer_path(@customer)
  end
  
  private

    def find_customer
      @customer = Customer.find_by(id: params[:id])
    end

    def cusomer_params
        params.require(:customer).permit(:name, :phone, :address)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
	def get_bg_color_of_status balance
		balance.pending? ? "pending_balance" : "no_dues_balance"
	end
end
	# def display_amount balance
	# 	if balance.nil?
	# 		"<p class='zero_bal'>0</p>".html_safe
	# 	elsif balance.advance_amount.present?
	# 		"<p class='adv_amt'>+ #{balance.advance_amount}/-</p>".html_safe
	# 	else
	# 		"<p class='due_amt'>- #{balance.due_amount}/-</p>".html_safe
	# 	end
	# end

app/views/customers/_reminder_sms.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"><strong><%= "To: #{@customer.name} (#{@customer.phone})"%></strong></h4>
    </div>
    <div class="modal-body">
     <%= form_tag send_reminder_sms_customer_path(@customer, page: params[:page]), method: :post  do %>
        <%= label_tag :message %>
        <%= text_area_tag :message,"", cols: 25, rows: 5, required: true, class: "form-control" %><br>    
        <%= submit_tag "SEND", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/customers/_search.html.erb
<%= search_form_for @q do |f| %>
  <div class="row">
    <div class="col-md-2">
      <label class="width-100">Shop</label>
        <%= f.select :billings_organization_id_eq, options_from_collection_for_select(@organizations, "id", "name"),  {:prompt => 'Select Shop'}, {:class => 'form-control mr-top'} %>
    </div>
    <div class="col-md-2">
      <label>Phone/Name</label>
      <%= f.search_field :phone_or_name_eq, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
    <div class="col-md-2">
      <!-- <button class="send_sms btn btn-primary">Download Xls</button> -->
      <!-- <button class="send_sms btn btn-primary">Download Xls</button> -->
      <%= link_to "download", "#", class: "send_sms btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/customers/index.html.erb
    <div class="main-panel">
      <%= render 'layouts/top_navbar'%>
      <%= render 'layouts/flash' %>
      <div class="content">
       <%= render 'customers/search' %>     
        <div class="row">
            <% @customers.each do |customer| %>
              <div class="col-md-3">
                <div class="card card-stats" id="<%= customer.id %>"> 

                  <div class="card-header card-header-warning card-header-icon">
                  <div class="form-check" style="float: left;">
                        <!-- <label class="form-check-label">
                          <input class="form-check-input" type="checkbox" value="" checked>
                          <span class="form-check-sign">
                            <span class="check"></span>
                          </span>
                        </label> -->
                      </div>                    
                    <p class="card-category">                      
                      <%= customer.name %></p>
                    <h3 class="card-title"><%= customer.phone %></h3>
                    <p class="card-category" style="margin-top: 30px;"></p>
                  </div>
                  <div class="card-footer">
                    <div class="stats">
                      <a href="customers/<%= customer.id %>">View</a>
                      <p style="margin-left: 90px;">Advance:- <span class="adv_amt"><%= customer.customer_balance_amount[0] %></span>&nbsp;&nbsp; &nbsp;&nbsp;Due:-  <span class="due_amt"> <%= customer.customer_balance_amount[1] %></span></p>
                      <!-- <a href="#pablo" style="margin-left: 70px;">Order:- <%= customer.billings.count %></a>                -->
                    </div>
                  </div>
                </div>
              </div>
            <% end %>    
          </div> 
          <div class="digg_pagination">
              <%= will_paginate @customers, :container => false %>
            
          </div>   
      </div>
    </div>
   

app/views/customers/reminder_sms.js.erb
$('#reminder_sms').html("<%= escape_javascript(render 'reminder_sms')%>");
$("#reminder_sms").modal();

app/views/customers/show.html.erb
    <div class="main-panel">
      <%= render 'layouts/top_navbar'%>
      <div class="content">
        <div class="container-fluid">
        	<div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Balances</h4>
                </div>
                <div class="card-body">
                  <div class="table-responsive  min-height-table">
                    <table class="table">
                      <thead class=" text-primary">                                    
                        <tr>
                          <!-- <th>ID</th> -->
                          <th>Billing</th>
                          <th>Due Amount</th>
                          <th>Advance Amount</th>
                          <th>status</th>
                          <th>Adjust billing</th>
                          <% if current_user.admin? %>
                          <th>Action</th>
                          <% end %>
                        </tr>
                      </thead>                                       
                        <tbody>
                          <% if @balances.present? %>
                            <% @balances.each do |balance| %>
                              <tr class="<%= get_bg_color_of_status(balance)%>">
                                <!-- <td class="show_pg"><%#= balance.id %></td> -->
                                <td class="show_pg"><%= balance.get_bill_number %> (<%= link_to "View", billing_path(balance.billing_id) %>)</td>
                                <td class="show_pg"><%= balance.due_amount %></td>
                                <td class="show_pg"><%= balance.advance_amount %></td>
                                <td class="show_pg"><%= balance.status %></td>   
                                <td class="show_pg"><%= balance.get_adjust_billing_number %></td>
                                <% if current_user.admin? %> 
                                <td class="show_pg">
                                  <%= link_to "Delete", customer_path(balance.customer_id, balance_id: balance.id), method: :delete %>
                                  <%= link_to "Clear","#" %>
                                  </td>
                                <% end %>
                              </tr>
                            <% end %>
                          <% else %>
                            <tr>
                              <th colspan="6">No Record Found</th>
                            </tr>
                          <% end %>
                        </tbody>  
                    </table>
                    <div class="digg_pagination">
                      <% unless params[:q].present? %>
                        <%#= will_paginate @balances, :container => false %>
                      <% end %>
                    </div>
                  </div>
                </div>
                 <div class="card-footer"><div class=" foo-ter">Pending <span style="margin-left: 100px;">Due Amount - <%= @balances.pending.sum(:due_amount) %> &nbsp; &nbsp; &nbsp; &nbsp; Advance Amount - <%= @balances.pending.sum(:advance_amount) %> </span>
                  <!-- <span style="float: right;">Advance Amount:- <%#= @attendances.sum(:advance_amount)%>/-</span></div> -->
                </div>
              </div>
            </div>         
          </div> 
          
        </div>
      </div>
    </div>