config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to=>"dashboards#welcome"

  resources :dashboards
  get "welcome", to: "dashboards#welcome"
  get "base", to: 'dashboards#index'

  resources :attendances, only: [:index, :create, :update] do
    get :payments, on: :collection
    get :payment_done, on: :collection
    post :delete_record, on: :collection
  end
  
  resources :billings, only: [:new, :create, :edit, :show, :update, :index, :destroy] do 
    put :update_status, on: :member
    get :cancel, on: :member
    post :delevery_done, on: :member
    put :delevery, on: :member
    get :get_bill_no, on: :collection
    patch :update_final_billing, on: :member
  	resources :carts, only: [:create, :new, :destroy]

  end 
  resources :customers, only: [:index, :show, :new, :create, :destroy] do 
    post :send_reminder_sms, on: :member
    get :reminder_sms, on: :member
    post :send_bulk_sms, on: :collection
    get :download, on: :collection
  end

  resources :employees, only: [:index, :create, :update, :destroy]

  resources :accounts, only: [:index, :create, :update] do
    post :delete_record, on: :collection
  end
  resources :vendor_billings do 
    get :get_monthaly_record, on: :collection
    get :payment_done, on: :collection
    get :change_amount, on: :member
    post :update_amount, on: :member
    post :delete_record, on: :collection
  end
  resources :extra, only: [:index] do
    post :create_item, on: :collection
    post :create_service, on: :collection
    get :billing, on: :collection
  end

  resources :csvs, only: [:index] do 
    get :get_monthly_record, on: :collection
    get "/download/:year/:month",  to: "csvs#download", on: :collection
    get "/destroy/:year/:month",  to: "csvs#destroy", on: :collection
  end
end

app/models/billing.rb
class Billing < ApplicationRecord
	# Association
	belongs_to :customer, optional: true
	belongs_to :organization, optional: true
	has_many :carts
	has_many :balances
	accepts_nested_attributes_for :carts, :reject_if => proc { |att| att[:item_id].blank? || att[:quantity].blank? || att[:amount].blank?}, :allow_destroy => true
	ransack_alias :customer, :phone
	# Validation
	validates :bill_no, presence: true
	validates :bill_no, uniqueness: { scope: :organization_id, message: "already exist in this organization" }
	# Scope
	scope :pending, -> { where('status = ?', "pending")}
	scope :complete, -> { where('status = ?', "complete")}
	scope :delivered, -> { where('status = ?', "delivered")}

	before_create :assign_status
	after_create :update_amount

	# Delegates
	delegate :name, to: :customer
	delegate :phone, to: :customer
    default_scope {order('id DESC')}


	def assign_status
		self.status = "pending"
	end

	def update_amount
		cart_total_amount = self.carts.sum(:amount)
		self.update_attributes(amount: cart_total_amount, final_amount: cart_total_amount)
	end

	def update_organization params
		self.update_attributes(bill_no: params[:bill_no], organization_id: params[:organization_id])
		self
	end

	def organization_exist?
		self.organization_id.present? && self.bill_no.present?
	end

	def customer_number_exist?
		customer.phone.present?
	end

	def send_order_confirm_sms
		if customer_number_exist?	
			message = "Your order no.#{self.bill_no} has been received. Will be delivered #{self.due_date.strftime("%d/%m/%Y")} amount Rs.#{self.final_amount}. Thank you for using PREMIUM DRY CLEANERS"
			Sms.send_sms(message, self.phone)
		end
	end

	def send_order_complete_sms
		if final_amount.present?
			message = "Your order no. #{self.bill_no} has been completed.please collect as soon as possible. Thank you for using PREMIUM DRY CLEANERS"
			Sms.send_sms(message, phone)	
		end
	end

	def create_customer phone, name
		c = Customer.find_by(phone: phone)
		if c.present?
			self.customer_id =  c.id
		else
			c = Customer.create(name: name, phone: phone)
			self.customer_id = c.id
		end
	end

	def complete?
		self.status == "complete"
	end

	def delivered?
		self.status == "delivered"
	end

	def get_phone
		self.persisted? ? self.phone : ""
	end

	def get_name
		self.persisted? ? self.name : ""
	end

	def update_customer_info cust_phone, cust_name
		self.customer.update_attributes(phone: cust_phone, name: cust_name)
	end

	def update_billing total_paid_amount
		if total_paid_amount.to_i > self.final_amount
			advance = total_paid_amount.to_i - self.final_amount
			self.balances.create(customer_id: customer_id, advance_amount: advance, due_amount: 0, status: "pending")
		elsif total_paid_amount.to_i < self.final_amount			
			due = self.final_amount - total_paid_amount.to_i
			self.balances.create(customer_id: customer_id, due_amount: due, advance_amount: 0, status: "pending")
		end
		self.update_attributes(status: "delivered", due_date: Date.today, total_paid_amount: total_paid_amount)
	end

	def balance
		self.balance_id.present? ? customer.balances.find_by(id: self.balance_id) : nil
	end
	def update_all_parameter
		total_cart_amounts = self.carts.sum(:amount)
		temp_final_amount = total_cart_amounts - self.advance_amount.to_i - self.discount_amount.to_i
	    self.update_attributes(receipt: false,	final_amount: temp_final_amount, amount: total_cart_amounts)
		get_adjust_balance(balance) if balance.present?	    
	end

	def update_final_billing_with_advance_amount params
		self.discount_amount = params[:discount_amount].to_i
	    self.advance_amount = params[:advance_amount].to_i
	    self.final_amount = self.amount - self.discount_amount - self.advance_amount
	    self.receipt = true
	    self.save
	    if params[:balance_id].present? # at this time this is bill number
	    	bill = Billing.find_by(bill_no: params[:balance_id])
		    pre_balance = self.customer.balances.pending.find_by(billing_id: bill.id)
		   	get_adjust_balance(pre_balance) if pre_balance.present?	 
		elsif balance.present?
			get_adjust_balance(balance)
		end 
	end

	def adjust_balance?
		self.customer.balances.pending.present? ? true : false
	end

	def adjust_balance
		bal = customer.balances.find_by(adjust_billing_id: self.id)
		bal.present? ? bal : false
	end

	def get_adjust_balance pre_balance
		if pre_balance.present?
			if pre_balance.due_amount > 0
				final_bal = self.final_amount + pre_balance.due_amount.to_i
			elsif pre_balance.advance_amount > 0
				final_bal = self.final_amount - pre_balance.advance_amount.to_i
			end
			self.update_attributes(final_amount: final_bal, balance_id: pre_balance.id)
			pre_balance.update_billing_status(self.id)
		end
	end

	def get_balance_amount_after_paid_final_amount
		if self.final_amount > self.total_paid_amount
			"<span class='due_amt'>(- #{final_amount - total_paid_amount})</span>".html_safe
		else
			"<span class='adv_amt'>(+ #{total_paid_amount - final_amount})</span>".html_safe
		end
	end

	def bill_no_of_balance_amount
		balance.billing
	end

	def get_total_final_amount
		total_paid_amount.present? ? total_paid_amount : final_amount
	end

	def self.to_csv(options = {}, billing_attributes = ["name", "phone", "bill_no", "amount", "discount_amount", "booking_date", "due_date"], customer_attributes=["name","phone" ])
    # attributes = %w{id name}
    CSV.generate(options) do |csv|
    	csv.add_row billing_attributes
    	all.each do |foo|
	      if foo.customer
	        values = foo.customer.attributes.slice(*customer_attributes).values 
	      end
	      values += foo.attributes.slice(*billing_attributes).values
	      csv.add_row values
	    end
    end
  end
	
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :find_billing, only: [:show, :update, :update_status, :cancel, :delevery, :delevery_done, :update_final_billing, :edit, :destroy]
  before_action :get_organizations, only: [:index, :show, :new, :create, :edit]

  def index
    @q = Billing.includes(:customer, :carts).ransack(params[:q])
    billings = @q.result
    if params[:q]
      @billings = billings.uniq
    else
      @billings = billings.paginate(:page => params[:page], :per_page => 30)
    end
  end

  def new
    if Billing.first.present?
      @billing = Billing.new(bill_no: Billing.first.bill_no+1)
    else
      @billing = Billing.new(bill_no: 23201)
    end
  end

  def show
  end

  def edit
    if @billing.delivered?
      redirect_to billing_path(@billing)
    else
      render 'new'
    end
  end

  def create
    @billing = Billing.new(billing_params)
    unless verify_phone_number(params[:phone])
      flash[:danger] = "Invalid contact number."
      render 'new' and return 
    end
      @billing.create_customer(params[:phone], params[:name])
    if @billing.save
      flash[:success] = "Successfully created."
      redirect_to billing_path(@billing)
    else
      flash[:danger] = @billing.errors.full_messages.join(',')
      render 'new'
    end
  end


  def update
    @billing.update_attributes(billing_params)
    @billing.update_customer_info(params[:phone], params[:name]) if params[:phone].present? || params[:name].present?
    @billing.update_all_parameter
    redirect_to billing_path(@billing)
  end

  def update_final_billing
    @billing.update_final_billing_with_advance_amount(params[:billing])    
    # @billing.send_order_confirm_sms
    redirect_to billing_path(@billing)
  end

  def update_status
    status = params[:status]=="reorder" ? "pending" : params[:status]
    @billing.update_attributes(status: status)
    # @billing.send_order_complete_sms if @billing.complete?
    redirect_to billings_path(page: params[:page])
  end

  def cancel
    @billing.update_attributes(status: "canceled")
    redirect_to billings_path
  end

  def delevery
  end

  def delevery_done
    @billing.update_billing(params[:total_paid_amount])  
    redirect_to billings_path(page: params[:page])
  end

  def get_bill_no
    org = Organization.find_by(id: params[:shop_id])
    bill_no = org.billings.first.bill_no + 1
    render json: {bill_no: bill_no}, status: 200
  end

  def destroy
     if @billing.delete
      flash[:success] = "Successfully Deleted"
     else
      flash[:danger] = "Something went wrong."
     end
     redirect_to billings_path
  end
  
  private

  def find_billing
    @billing = Billing.find_by(id: params[:id])
  end

  def billing_params
    params.require(:billing).permit(:booking_date, :bill_no, :due_date,:organization_id, carts_attributes: [:id, :quantity, :item_id, :amount, :service_id, :remark, :_destroy])
  end

  def verify_phone_number phone_number
    phone_number.length == 10 ? true : false
  end

end

app/helpers/billings_helper.rb
module BillingsHelper
	def get_status status
		case status
			when "pending"
			  return "complete" 
			when "complete"
			  return "delivered"
			when "canceled"
			  return "reorder"
			else
				return "done"
		end
	end

	def get_icon status
		case status
			when "pending"
			  return "fa fa-ellipsis-h" 
			when "complete"
			  return "fa fa-check-circle-o"
			when "delivered"
			  return "fa fa-handshake-o"
			else
				return "fa fa-close"
		end
	end

	def billing_title billing
		billing.persisted? ? "EDIT BILLING" : "NEW BILLING"
	end

	def submit_tag_title billing
		billing.persisted? ? "UPDATE" : "SUBMIT"
	end

	def billing_cancel?(billing)
		billing.status == "canceled" ? "cancel" : ""
	end

	def bal_status billing
		if billing.customer.balances.present?
			bal = billing.customer.balances.last
			balance = (bal.status == "pending" || bal.adjust_billing_id == billing.id) ? bal : nil
			if balance.present?
				balance.get_balance_status
			end
		end

	end

	def balance_status(billing)
		bal_status(billing).present? ? (bal_status(billing).first[0].to_s.titleize) : "" 
	end

	def balance_amount(billing)		
		bal_status(billing).present? ? positiv_negetive_bal(billing) : 0
	end

	def positiv_negetive_bal(billing)
		if bal_status(billing).first[0] == :due_amount
			"+#{bal_status(billing).first[1].to_i}/-"
		else
			"-#{bal_status(billing).first[1].to_i}/-"
		end
	end

	def get_booking_date(billing)
		billing.booking_date.present? ? billing.booking_date : Date.today
	end

	def get_adjust_balance_status balance
		if balance.advance_amount > 0
			"-#{balance.advance_amount}/-"
		else
			"+#{balance.due_amount}/-"
		end
	end

	def billing_sum billings, status
		if status == "delivered"
			billings.to_a.sum { |e| e.total_paid_amount.to_i }
		else
			billings.to_a.sum { |e| e.final_amount.to_i }
			# billings.map{|b| b.final_amount}.sum
		end
	end

	def advance_sum billings
		billings.to_a.sum { |e| e.advance_amount.to_i }
	end
end

app/views/billings/_bill_search.html.erb
 <%= search_form_for @q do |f| %>
  <div class="row">
    <div class="col-md-2">
      <label class="bmd-label-floating">Billing Date</label>
      <%= f.date_field :booking_date_eq, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <label class="bmd-label-floating">Service</label>
      <%= f.select :carts_service_id_eq, options_from_collection_for_select(Service.all, "id", "name", @q.carts_service_id_eq),  {:prompt => 'Select Service'}, {:class => 'form-control mr-top'} %>
    </div>
    <div class="col-md-2">
      <label class="bmd-label-floating">Delivery Date</label>
      <%= f.date_field :due_date_eq, class: "form-control" %>
    </div>
    <div class="col-md-1">
      <label>Status</label>
      <%= f.select :status_eq, options_for_select([ "pending", "complete", "delivered" ], @q.status_eq),  {:prompt => 'Select'}, {:class => 'form-control mr-top'} %>
      
    </div>
    <div class="col-md-1">
      <label>Bill no.</label>
      <%= f.search_field :bill_no_eq, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <label>Phone/Name</label>
      <%= f.search_field :customer_phone_or_customer_name_eq, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.submit "Search", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/billings/_delevery.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>STATUS: <span style="color: green;">Delevered</span></h3>
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"><strong></strong></h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <%= form_for @billing, url: delevery_done_billing_path(@billing, page: params[:page]), method: :post  do |f| %>
         		<h3></h3>    
            <div class="form-group">
              <%= label_tag :Total_paid_amount %>
              <%= number_field_tag :total_paid_amount,"", class: "form-control" %><br>  
            </div>
            <div class="form-group"> 
              <%= submit_tag "SEND", class: "btn btn-primary" %>
            </div>
          <% end %>
      </div>
      <div class="col-md-1"></div>
    </div>
    </div>
  </div>
</div>

app/views/billings/_status.html.erb
<% if status == "delivered" %>
	<%= link_to status.titleize, delevery_billing_path(billing, status: status, page: page), method: :put, remote: true, class: "#{status} btn btn-primary btn-xs bg_#{status}" %>
<% else %>	
	<%= link_to status.titleize, update_status_billing_path(billing, status: status, page: page), method: :put, class: "#{status} btn btn-primary btn-xs bg_#{status}" %>
<% end %>

app/views/billings/delevery.js.erb
$('#reminder_sms').html("<%= escape_javascript(render 'delevery')%>");
$("#reminder_sms").modal();

app/views/billings/index.html.erb
    <div class="main-panel">
      <%= render 'layouts/top_navbar'%>
      <div class="content">
       <%= render 'billings/bill_search' %>
        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Billings</h4>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">                                    
                        <tr>
                          <th>Booking</th>
                          <th>Status</th>
                          <th>Delivery Date</th>
                          <th>Bill No.</th>
                          <th>Phone</th>
                          <th>Name</th>
                          <th>Advance</th>
                          <th>Due Amount</th>
                          <th></th>
                          <th>Action</th>
                        </tr>
                      </thead>                                       
                        <tbody>
                          <% if @billings.present? %>
                            <% @billings.each do |billing| %>
                              <tr id="billing_<%= billing.id %>" class="<%= billing_cancel?(billing) %>">
                                <td class="show_pg"><%= billing.booking_date.strftime("%d/%m/%Y") %></td>
                                <td class="<%= billing.status %>"><%= billing.status.titleize %></td>
                                <td class="show_pg"><%= billing.due_date.strftime("%d/%m/%Y") if billing.due_date.present? %></td>
                                <td class="show_pg"><%= billing.bill_no %></td>
                                <td class="show_pg"><%= billing.phone %></td>
                                <td class="show_pg"><%= billing.name %></td> 
                                <td class="show_pg"><%= billing.advance_amount %></td>  
                                <td class="show_pg"><%= billing.get_total_final_amount %></td>                                
                                <td><%= render 'status', status: get_status(billing.status), billing: billing, page: params[:page]   %></td>
                                <td>
                                  <%= link_to "View", billing_path(billing), class: "btn btn-primary btn-xs" %>
                                  <% if current_user.admin? %>
                                    <%= link_to "Edit", edit_billing_path(billing), class: "btn btn-primary btn-xs" %>
                                    <%= link_to "Delete", billing_path(billing), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs" %>
                                  <% end %>
                                </td>
                              </tr>
                            <% end %>
                          <% else %>
                            <tr>
                              <th colspan="6">No Record Found</th>
                            </tr>
                          <% end %>
                        </tbody>  
                    </table>
                    <div class="digg_pagination">
                      <% unless params[:q].present? %>
                        <%= will_paginate @billing, :container => false %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <% if params[:q] && params[:q][:status_eq] %>
                <div class="card-footer"><div class=" foo-ter">Total<span style="margin-left: 180px;">  &nbsp;&nbsp; &nbsp;&nbsp;Advance Amount:- <%= advance_sum(@billings)%> &nbsp;&nbsp; &nbsp;&nbsp; <%=  params[:q][:status_eq].titleize %> Amount:- &nbsp;&nbsp;&nbsp;&nbsp;<%= billing_sum(@billings, params[:q][:status_eq]) %>/-</span></div>
                  
                </div>
                <% end %>
              </div>
            </div>         
          </div>        
      </div>
    </div>

app/views/billings/show.html.erb
<%= stylesheet_link_tag "application", media: "print" %>
    <div class="main-panel">
      <%= render 'layouts/top_navbar'%>
      <%= render 'layouts/flash' %>
        <div class="content">
            <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">New Billing</h4>
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-3">
                      <p>BillNo. <%= @billing.bill_no %></p>
                      <p>Date:- <%= @billing.created_at.strftime("%d/%m/%Y")%></p>
                      <p>Custome Name:- <%= @billing.name %></p>
                      <p>Custome Phone:- <%= @billing.phone %></p>
                      <p>Due Date:- <%= @billing.due_date.strftime("%d/%m/%Y")%></p>
                      <% if @billing.total_paid_amount.present? %>
                       <p>Total Paid Amount:- <%= @billing.total_paid_amount %></p>
                        <p>Balance Amount:- <%= @billing.get_balance_amount_after_paid_final_amount %></p>
                      <% end %>

                    </div>
                    <div class="col-md-9">
                      <div class="row row-top">
                          <div class="col-md-4"><h4>Items</h4></div>
                          <div class="col-md-4"><h4>Service</h4></div>
                          <div class="col-md-2"><h4>Quantity</h4></div>
                          <div class="col-md-2"><h4>Amount</h4></div>
                      </div>
                      <div>
                      <% @billing.carts.each do |cart| %>
                        <div class="row" style="margin-top: 15px;">
                          <div class="col-md-4"><%= cart.item.name %><%= "(#{cart.remark})" if cart.remark.present?%></div>
                          <div class="col-md-4"><%= "(#{cart.service.name})" if cart.service.present?%></div>
                          <div class="col-md-2"><%= cart.quantity %></div>
                          <div class="col-md-2"><%= cart.amount %>/-</div>
                        </div>
                      <% end %>
                      </div>
                      <div class="row row-top" style="margin-top: 20px;">
                        <div class="col-md-4">Total Amount -</div>
                        <div class="col-md-4"></div>
                        <div class="col-md-2"><%= @billing.carts.sum(:quantity) %></div>
                        <div class="col-md-2"><%= @billing.amount %>/-</div>                        
                      </div>              
                        <% if @billing.receipt %>
                          <div class="row">   
                            <div class="col-md-4"></div>                   
                            <div class="col-md-4">
                              <div class="form-group">
                                <p class="">Advance -</p>
                              </div>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-2">
                              <div class="form-group">
                                <p>-<%= @billing.advance_amount %>/-</p>
                              </div>
                            </div>
                          </div>
                          <div class="row">       
                            <div class="col-md-4"></div>               
                            <div class="col-md-4">
                              <div class="form-group">
                                <p class="">Discount -</p>
                              </div>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-2">
                              <div class="form-group">
                                <p>-<%= @billing.discount_amount %>/-</p>
                              </div>
                            </div>
                          </div>
                          <% if @billing.adjust_balance %>
                          <div class="row">      
                            <div class="col-md-4"></div>                
                            <div class="col-md-4">
                              <div class="form-group mr-20">
                                <p class="">Adjust Balance(<%=link_to @billing.bill_no_of_balance_amount.bill_no, billing_path(@billing.bill_no_of_balance_amount) %>)</p>
                              </div>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-2">
                              <div class="form-group mr-20">
                                <p><%= get_adjust_balance_status(@billing.adjust_balance) %></p>
                              </div>
                            </div>
                          </div>
                          <% end %>
                          <div class="row row-top">
                            <div class="col-md-4"></div>                      
                            <div class="col-md-4">
                              <div class="form-group mr-20">
                                <p class="">Final Amount</p>
                              </div>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-2">
                              <div class="form-group mr-20">
                                <p><%= @billing.final_amount %>/-</p>
                              </div>
                            </div>
                          </div>
                        <% else %>                   
                        <%= form_for @billing, url: update_final_billing_billing_path(@billing) do |f| %>
                          <div class="row">
                            <div class="col-md-4"></div>
                            <div class="col-md-4">
                              <div class="form-group">
                                <p class="">Advance</p>
                              </div>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-2">
                              <div class="form-group">
                                <% if @billing.advance_amount.present? %>
                                  <%= f.number_field :advance_amount, class: "form-control", readonly: true %>
                                <% else %>
                                  <%= f.number_field :advance_amount, class: "form-control" %>
                                <% end %>
                              </div>
                            </div>
                          </div>
                            <div class="row">
                                <div class="col-md-4"></div>
                                <div class="col-md-4">
                                  <div class="form-group">
                                    <p class="">Discount</p>
                                  </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-2">
                                  <div class="form-group">
                                    <%= f.number_field :discount_amount, class: "form-control" %>
                                  </div>
                                </div>
                            </div>
                          <% if @billing.adjust_balance %>
                            <div class="row">      
                              <div class="col-md-4"></div>                
                              <div class="col-md-4">
                                <div class="form-group mr-20">
                                  <p class="">Adjust Balance(<%=link_to @billing.bill_no_of_balance_amount.bill_no, billing_path(@billing.bill_no_of_balance_amount) %>)</p>
                                </div>
                              </div>
                              <div class="col-md-2"></div>
                              <div class="col-md-2">
                                <div class="form-group mr-20">
                                  <p><%= get_adjust_balance_status(@billing.adjust_balance) %></p>
                                </div>
                              </div>
                            </div>
                          <% end %>                          
                          
                          <% if @billing.adjust_balance? %>
                              <div class="row">      
                                <div class="col-md-4"></div>                
                                <div class="col-md-4">
                                  <div class="form-group mr-20">
                                    <p class="">Adjust Balance ID</p>
                                  </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-2">
                                  <div class="form-group mr-20">
                                    <p><%= f.number_field :balance_id, class: "form-control" %></p>
                                  </div>
                                </div>
                              </div>
                          <% end %>                       
                           <div class="row row-top">      
                            <div class="col-md-4"></div>                
                            <div class="col-md-4">
                              <div class="form-group mr-20">
                                <p class="">Final Amount</p>
                              </div>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-2">
                              <div class="form-group mr-20">
                                <p><%= @billing.final_amount %>/-</p>
                              </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-md-10"></div>
                            <div class="col-md-2">
                              <%= f.submit "Done", class: "btn btn-primary" %>                              
                            </div>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>            
          </div>
        </div>
      </div>
    </div>
<style type="text/css">
    .row-top{
        background: #964daf;
        color: white;
        padding: 4px;
        border-radius: 3px;
        margin-right: -4px;
        margin-left: -4px;
    }
    .bd-top{
      border-top: 2px solid black;
      border-bottom: 2px solid black;
    }
   
</style>

<script type="text/javascript">    
    function PrintDiv() {   
       var divToPrint = document.getElementById('print');
       var popupWin = window.open('', '_blank', 'width=900,height=700');
       popupWin.document.open();
       popupWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
        popupWin.document.close();
            }
 </script>