config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to=>"dashboards#welcome"

  resources :dashboards
  get "welcome", to: "dashboards#welcome"
  get "base", to: 'dashboards#index'

  resources :attendances, only: [:index, :create, :update] do
    get :payments, on: :collection
    get :payment_done, on: :collection
    post :delete_record, on: :collection
  end
  
  resources :billings, only: [:new, :create, :edit, :show, :update, :index, :destroy] do 
    put :update_status, on: :member
    get :cancel, on: :member
    post :delevery_done, on: :member
    put :delevery, on: :member
    get :get_bill_no, on: :collection
    patch :update_final_billing, on: :member
  	resources :carts, only: [:create, :new, :destroy]

  end 
  resources :customers, only: [:index, :show, :new, :create, :destroy] do 
    post :send_reminder_sms, on: :member
    get :reminder_sms, on: :member
    post :send_bulk_sms, on: :collection
    get :download, on: :collection
  end

  resources :employees, only: [:index, :create, :update, :destroy]

  resources :accounts, only: [:index, :create, :update] do
    post :delete_record, on: :collection
  end
  resources :vendor_billings do 
    get :get_monthaly_record, on: :collection
    get :payment_done, on: :collection
    get :change_amount, on: :member
    post :update_amount, on: :member
    post :delete_record, on: :collection
  end
  resources :extra, only: [:index] do
    post :create_item, on: :collection
    post :create_service, on: :collection
    get :billing, on: :collection
  end

  resources :csvs, only: [:index] do 
    get :get_monthly_record, on: :collection
    get "/download/:year/:month",  to: "csvs#download", on: :collection
    get "/destroy/:year/:month",  to: "csvs#destroy", on: :collection
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	def index
		@title = "sdasA"
	end

	def welcome
		render layout: "devise"
	end
end

app/views/dashboards/index.html.erb
    <div class="main-panel">
      <%= render 'layouts/top_navbar'%>
      <div class="content">
        <div class="container-fluid">
        </div>
      </div>
    </div>

app/views/dashboards/welcome.html.erb
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
      <div class="navbar-wrapper" style="font-size: 32px;">
        <a href="/" style="color: white;">PremiumDryCleaners</a>
      </div>
      
      <div class="collapse navbar-collapse justify-content-end">
        <ul class="navbar-nav" style="font-size: 28px;">
          
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Home", billings_path, class: "nav-space" %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path,  class: "nav-space" %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "LOGIN", new_user_session_path, class: "nav-space" %>
            </li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->
  <div class="page-header clear-filter">
    <div class="page-header-image" style="background-image: url('/assets/cover1.jpg');"></div>
    <div class="content-center">
      <div class="row">
        <!-- <div class="col-md-2"></div> -->
        <div class="col-md-12">
          <div class="brand" style="font-size: 60px; font-weight: 600;">
            WE ARE EXPERT CLEANER

            <!-- <h1><span>W</span>elcome <span>t</span>o<br><span>p</span>remium<br><span>d</span>ry <span>c</span>leaners</h1> -->
          </div>
        </div>
        <!-- <div class="col-md-2"></div> -->
      </div>
    </div>
  </div>